### ISSUE TITLE
To-do list: common tools

### ISSUE THREAD

**Issue by I-am-Erk** [I-am-Erk/CDDA-Tilesets#12]
This is not an exhaustive list of tools in the game but a list of common tool items that need icons. If an icon doesn't have any subcategories, we just need an "on ground" version - with a hard black line along the bottom edge as is standard.

Remember, items should be roughly to scale. For small items like handheld tools it might be easier to draw them in a 16x16 canvas to keep you on track.

- [ ] anvil
- [ ] binoculars
- [ ] bone needle
   - [ ] wielded
   - [x] on ground
- [ ] brazier
   - [ ] as furniture
   - [ ] folded on ground
- [ ] butcher knife
   - [ ] wielded
   - [x] on ground
- [ ] candle
- [ ] chainsaw (gas)
   - [ ] wielded
   - [ ] on ground
- [ ] circular saw
   - [ ] wielded
   - [ ] on ground
- [ ] cot
   - [ ] as furniture
   - [ ] folded on ground
- [x] crowbar
   - [x] wielded
   - [x] on ground
- [x] clay crucible
- [ ] crucible
- [ ] digging stick
   - [ ] wielded
   - [ ] on ground
- [ ] dogfood
- [ ] drill
   - [ ] wielded
   - [ ] on ground
- [ ] electric jackhammer / hammer drill
- [ ] electric lantern
- [ ] fire extinguisher
- [x] flashlight
   - [x] wielded
   - [x] on ground
- [ ] frying pan (aluminum version)
   - [ ] wielded
   - [ ] on ground
- [ ] Geiger counter
- [x] hacksaw
- [ ] hand drill
- [ ] Halligan bar
   - [ ] wielded
   - [ ] on ground
- [ ] hammer
   - [ ] wielded
   - [x] on ground
- [ ] hatchet
   - [ ] wielded
   - [ ] on ground
- [x] heavy duty flashlight
   - [x] wielded
   - [x] on ground
- [ ] hoe
   - [ ] wielded
   - [ ] on ground
- [ ] hotplate
- [ ] jack
- [ ] jackhammer (gas)
- [ ] large tent (collapsed)
- [ ] lighter
- [ ] lightstrip
- [ ] machete
   - [ ] wielded
   - [ ] on ground
- [x] makeshift welder
- [ ] matchbook
- [ ] meat cleaver
   - [ ] wielded
   - [x] on ground
- [ ] metalworking chisel
- [ ] military ID card
- [ ] mop
   - [ ] wielded
   - [ ] on ground
- [ ] mp3 player
- [ ] nailgun
   - [ ] wielded
   - [ ] on ground
- [ ] pair of bolt cutters
- [ ] pair of metal tongs
- [ ] pickaxe
   - [ ] wielded
   - [ ] on ground
- [ ] picklock kit
- [ ] pocket knife
   - [ ] wielded
   - [ ] on ground
- [ ] pot
- [ ] radio
- [ ] rag
- [ ] restaurant guide
- [ ] road map
- [ ] rollmat
   - [ ] as furniture
   - [ ] folded on ground
- [ ] scalpel
- [ ] science ID card
- [ ] scissors
   - [ ] wielded
   - [x] on ground
- [ ] screwdriver
   - [ ] wielded
   - [ ] on ground
- [x] sewing kit
- [ ] shovel
   - [ ] wielded
   - [ ] on ground
- [ ] sledgehammer
   - [ ] wielded
   - [ ] on ground
- [ ] soldering iron
- [ ] spray can
- [ ] steak knife
   - [ ] wielded
   - [ ] on ground
- [ ] stone axe
   - [ ] wielded
   - [ ] on ground
- [x] stone hammer
   - [x] wielded
   - [x] on ground
- [ ] stone pot
- [ ] stone shovel
   - [ ] wielded
   - [ ] on ground
- [ ] syringe
- [ ] tent (packed up)
- [ ] torch
   - [ ] wielded
   - [ ] on ground
- [ ] two-way radio
- [ ] umbrella
   - [ ] wielded
   - [ ] on ground
- [x] usb drive
- [ ] vegetable cleaver
   - [ ] wielded
   - [x] on ground
- [ ] vibrator
   - [ ] wielded
   - [ ] on ground
- [ ] water purifier
- [x] welder
- [ ] wood axe
   - [ ] wielded
   - [ ] on ground
- [x] wood saw
- [ ] wrench
   - [ ] wielded
   - [ ] on ground
- [ ] x-acto knife
   - [ ] wielded
   - [ ] on ground

Feel free to suggest things I've missed
