### ISSUE TITLE
To-do list: basic vehicle parts

### ISSUE THREAD

**Issue by I-am-Erk** [I-am-Erk/CDDA-Tilesets#33]
BOARDS
Boards and frames multitile into horizontal, horizontal 2, vertical, vertical 2, cover, ne, nw, se, sw, and a broken variant for all those.
- [ ] board "A metal wall.  Keeps zombies outside the vehicle and prevents people from seeing through it.",
   - [ ] hdboard "A strong metal wall.  Keeps zombies outside the vehicle and prevents people from seeing through it.", looks_like board
- [ ] clothboard "A cloth wall.  Keeps zombies outside the vehicle and prevents people from seeing through it.",
- [ ] cloth_halfboard "A half-height cloth wall.  Keeps zombies outside the vehicle but allows people to see over it.",
- [ ] halfboard "A half-height metal wall.  Keeps zombies outside the vehicle but allows people to see over it.",
   - [ ] hdhalfboard "A half-height strong metal wall.  Keeps zombies outside the vehicle but allows people to see over it.",
   - [ ] xlhalfboard "A half-height thin metal wall.  Keeps zombies outside the vehicle but allows people to see over it.",
- [ ] stowboard "A metal wall with a storage locker.  Keeps zombies outside the vehicle and prevents people from seeing through it.",
   - [ ] hdstowboard "heavy duty stow board",
- [ ] woodboard "A wooden wall.  Keeps zombies outside the vehicle and prevents people from seeing through it.",
- [ ] woodhalfboard "A half-height wooden wall.  Keeps zombies outside the vehicle but allows people to see over it.",

FRAMES
Boards and frames multitile into horizontal, horizontal 2, vertical, vertical 2, cover, ne, nw, se, sw, and a broken variant for all those.
- [ ] folding_frame
- [ ] folding_wooden_frame
- [ ] frame
- [ ] frame_wood
- [ ] frame_wood_light
- [ ] hdframe
- [ ] xlframe

WHEELS
- [ ] wheel_mount_light: A piece of metal with holes suitable for a bike or motorbike wheel
   - [ ] wheel_mount_light_steerable
- [ ] wheel_mount_medium: Connection where wheels can be connected on. This particular one is fit for normal car wheels.
   - [ ] wheel_mount_medium_steerable
- [ ] wheel_mount_heavy: Connection where wheels can be connected on. This particular one is fit for large car wheels
   - [ ] wheel_mount_heavy_steerable
- [ ] rail_wheel: A strong metal wheel.  A flange helps keep it on a rail, but makes it perform terribly when not on a rail
   - [ ] rail_wheel_steerable
- [ ] roller_drum
- [ ] wheel
   - [ ] wheel_slick: racing slick, looks like wheel
   - [ ] wheel_armor: "A very strong, armored metal wheel." "looks_like": wheel
   - [ ] wheel_motorbike looks like wheel
   - [ ] wheel_motorbike_or off-road motorbike wheel
   - [ ] wheel_wide
   - [ ] wheel_wide_or
- [ ] wheel_bicycle
   - [ ] wheel_bicycle_or, "off-road bicycle wheel"
   - [ ] wheel_unicycle "looks_like": "wheel_bicycle"
   - [ ] wheel_wheelchair "looks_like": "wheel_bicycle"
- [ ] wheel_caster
- [ ] wheel_small
- [ ] wheel_tricycle "A set of three plastic wheels, with a larger one in the front, mounted with bolts."
- [ ] wheel_wood
   - [ ] wheel_wood_b banded wooden cart wheel
